version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php-car-decoder
    volumes:
      - type: bind
        source: .
        target: /app

    networks:
      - php-app-network

  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8300:80
    networks:
      - php-app-network

networks:
  php-app-network:
    driver: bridge

volumes:
  db_data: